backend:
  name: github
  repo: cassiozen/NG

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - { label: "Body", name: "body", widget: "markdown" }
